---
title: "Publications"
---

<hr>

## Peer-reviewed publications

<ol reversed>

<li>**Duthie, AB**, and VJ Luque. 2025. Foundations of ecological and evolutionary change. *Ecology and Evolution*. *In press*. [[Pre-print](https://arxiv.org/abs/2409.10766)]

<li>Tomsin, I, **AB Duthie**, N Bunnefeld, H Leirs, J Casaer, and N Beenaerts. 2025. Evaluating Management Scenarios for the European Hamster (*Cricetus cricetus*) Using Quantitative Models. *Ecology and Evolution* 15:e72353. [10.1002/ece3.72353](https://doi.org/10.1002/ece3.72353) [[PDF](ms/TomsinEtAl2025.pdf)]</li> 

<li>Anderson, HK, **AB Duthie**, CW McDougall, RS Quilliam, and H Price. 2025. The impact
of the cost-of-living crisis on water poverty in Scotland: A lived-experience analysis. *Utilities Policy*. 302:110915. [10.1016/j.jup.2025.101983](https://doi.org/10.1016/j.jup.2025.101983)  [[PDF](ms/AndersonEtAl2025.pdf)]</li>

<li>Fleming, M, A Bell, HR Harison, J Herrera, **AB Duthie**, R Kramer, and OS Rakotonarivo. 2025. Impact of price shocks and payments on crop diversification and forest use among Malagasy vanilla farmers. *Biological Conservation*. 302:110915 [10.1016/j.biocon.2024.110915](https://www.sciencedirect.com/science/article/pii/S0006320724004774?dgcid=coauthor).  [[PDF](ms/FlemingEtAl2025.pdf)]</li>

<li>Bradfer-Lawrence, T, **AB Duthie**, C Abrahams, A Mat$\acute{a}$$\check{s}$, RJ Barnett, A Beeston, J Darby, B Dell, N Gardner, A Gasc, B Heath, N Howells, M Janson, M.-V. Kyoseva, T. Luypaert, O. C. Metcalf, A. E. Nousek-McGregor, F. Poznansky, S. R. P-J Ross, S Sethi, S Smyth, E Waddell, and JSP Froidevaux. 2024. A practical manual for defining, generating and understanding current and future acoustic indices. *Methods in Ecology and Evolution*. [10.1111/2041-210X.14357](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.14357).  [[PDF](ms/Bradfer-LawrenceEtAl2024.pdf)] [[Code](https://github.com/bradduthie/ecoacoustic_website)]</li>

 <li>**Duthie, AB**, R Mangan, CR McKeon, MC Tinsley, and LF Bussière. 2023. resevol: An R package for spatially explicit models of pesticide resistance given evolving pest genomes. *PLoS Computational Biology*. 19:e1011691. [10.1371/journal.pcbi.1011691](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011691) [[PDF](ms/DuthieEtAl2023.pdf)] [[Supporting Information 1](ms/DuthieEtAl2023_S1.pdf)] [[Supporting Information 2](ms/DuthieEtAl2023_S2.pdf)] [[Website](http://bradduthie.github.io/resevol)] [[Code](https://github.com/bradduthie/resevol)] [[CRAN](https://cran.r-project.org/package=resevol)]</li>
 
 <li>Fell, A, TSF. Silva, **AB Duthie**, and D Dent. 2023. A global systematic review of frugivorous animal tracking studies and the estimation of seed dispersal distances. *Ecology and Evolution*. 13:e10638. [10.1002/ece3.10638](https://onlinelibrary.wiley.com/doi/10.1002/ece3.10638) [[PDF](ms/Fell2023EtAl.pdf)] [[Appendix 1](ms/Fell2023EtAl_A1.docx)] [[Appendix 2](ms/Fell2023EtAl_A2.xlsx)] [[Appendix 3](ms/Fell2023EtAl_A3.xlsx)] [[Appendix 4](ms/Fell2023EtAl_A4.xlsx)]</li>

 <li>Bell, AR, OS Rakotonarivo, A Bhargava, **AB Duthie**, W Zhang, B Sargent, S Lewis, and A Kipchumba. 2023. Payments don't reconcile agriculture and conservation. *Communications Earth and Environment*. 4:27. [10.1038/s43247-023-00689-6](https://www.nature.com/articles/s43247-023-00689-6) [[PDF](ms/BellEtAl2023.pdf)]</li>
 
 <li>Marshall, BM, and **AB Duthie**. 2022. abmAnimalMovement: An R package for simulating animal movement using an agent-based model. *F1000 Research*. [https://f1000research.com/articles/11-1182](https://f1000research.com/articles/11-1182) [version 1; peer review: 1 approved with reservations]. [[PDF](ms/Marshall_Duthie2022.pdf)]</li>

 <li>Jones, IL, A Timoshenko, I Zuban, K Zhadan, JJ Cusack, **AB Duthie**, ID Hodgson, J Minderman, RA Pozo, RC Whytock, and N Bunnefeld. 2022. Achieving international biodiversity targets: learning from migratory waterfowl management. *Journal of Applied Ecology*. 59:1911-1924. [10.1111/1365-2664.14198](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2664.14198) [[PDF](ms/JonesEtAl2022.pdf)]</li>

 <li>Bach, A, J Minderman, N Bunnefeld, A Mill, and **AB Duthie**. 2022. Intervene or wait? Modelling the timing of intervention in conservation conflicts adaptive management under uncertainty. *Ecology and Society*. 27 (3):3. [10.5751/ES-13341-270303](https://ecologyandsociety.org/vol27/iss3/art3/) [[Pre-print](https://www.biorxiv.org/content/10.1101/2021.08.27.457773v2)] [[PDF](ms/BachEtAl2022.pdf)]</li>

 <li>Dawson, S, C Pérez Carmona, M Gonzalez Suarez, M Jönsson, F de Carvalho, M Mallen-Cooper, Y Melero, H Moor, J Simaika, and **AB Duthie**. 2021. The traits of 'trait ecologists': an analysis of the use of trait and functional trait terminology. *Ecology and Evolution*. 11:16434-16445. [10.1002/ece3.8321](https://onlinelibrary.wiley.com/doi/10.1002/ece3.8321) [[PDF](ms/DawsonEtAl2021.pdf)]</li>

 <li>Rakotonarivo, OS, A Bell, B Dillon, **AB Duthie**, A Kipchumba, R Rasolofoson, J Razafimanahaka, and N Bunnefeld. 2021. Experimental evidence on the impact of payments and property rights on forest user decisions. *Frontiers in Conservation Science*. 2:661987. [10.3389/fcosc.2021.661987](https://www.frontiersin.org/articles/10.3389/fcosc.2021.661987) [[PDF](ms/RakotonarivoEtAl2021b.pdf)]</li>
 
 <li>**Duthie, AB**, J Minderman, OS Rakotonarivo, G Ochoa, and N Bunnefeld. 2021. Online multiplayer games as virtual laboratories for collecting data on socio-ecological decision-making. *Conservation Biology*. 35:1051-1053. [10.1111/cobi.13633](https://conbio.onlinelibrary.wiley.com/doi/10.1111/cobi.13633) [[PDF](ms/DuthieEtAl2021.pdf)]</li>
 
 <li>Rakotonarivo, OS, A Bell, K Abernathy, J Minderman, **AB Duthie**, S Redpath, A Keane, H Travers, S Bourgeois, L-L Moukagni, JJ Cusack, IL Jones, RA Pozo, and N Bunnefeld. 2021. The role of incentive-based instruments and social equity in conservation conflict interventions. *Ecology and Society*. 26:8. [10.5751/ES-12306-260208](https://www.frontiersin.org/articles/10.3389/fcosc.2021.661987) [[PDF](ms/RakotonarivoEtAl2021.pdf)]</li>

 <li>Pozo, RA, E LeFlore, **AB Duthie**, N Bunnefeld, IL Jones, J Minderman, OS Rakotonarivo, and JJ Cusack. 2021. A multispecies assessment of wildlife impacts on localcommunity livelihoods. *Conservation Biology*. 35:297-306. [10.1111/cobi.13565](https://conbio.onlinelibrary.wiley.com/doi/10.1111/cobi.13565) [[PDF](ms/PozoEtAl2020.pdf)] [[Appendix S1](ms/PozoEtAl2020_sup.pdf)]</li>

 <li>Rakotonarivo, OS, IL Jones, A Bell, **AB Duthie**, JJ Cusack, J Minderman, J Hogan, I Hodgson, and N Bunnefeld. 2021. Experimental evidence for conservation conflict interventions: the importance of financial payments, community trust and equity attitudes. *People and Nature*. 3:162-175. [10.1002/pan3.10155](https://besjournals.onlinelibrary.wiley.com/doi/10.1002/pan3.10155). [[PDF](ms/RakotonarivoEtAl2020.pdf)] [[SI 1](RakotonarivoEtAl2020_sup1.pdf)] [[SI 2](http://bradduthie.github.io/RakotonarivoEtAl2020_sup2.pdf)]</li>

 <li>Nilsson, L, J Minderman, N Bunnefeld, and **AB Duthie**. 2021. Effects of stakeholder empowerment on crane population and agricultural production. *Ecological Modelling*. 404:109396. [10.1016/j.ecolmodel.2020.109396](https://www.sciencedirect.com/science/article/pii/S0304380020304609?via%3Dihub). [[PDF](ms/NilssonEtAl2021.pdf)] [[Supplementary Material 1](ms/NilssonEtAl2021_sup1.pdf)] [[Supplementary Material 2](ms/NilssonEtAl2021_sup2.pdf)]</li>

 <li>**Duthie, AB**. 2020. Component response rate variation underlies the stability of highly complex finite systems. *Scientific Reports*. 10: 8296. [10.1038/s41598-020-64401-w](https://www.nature.com/articles/s41598-020-64401-w). [[PDF](ms/Duthie2020.pdf)] [[Pre-print](https://arxiv.org/abs/1806.01029)] [[Code](https://github.com/bradduthie/RandomMatrixStability)] [[Website](https://bradduthie.github.io/RandomMatrixStability/index.html)]</li>
 
 <li>Cusack, JJ, **AB Duthie**, IL Jones, J Minderman, RA Pozo, OS Rakotonarivo, S Redpath, and N Bunnefeld. 2020. Integrating conflict, lobbying, and compliance to predict the sustainability of natural resource use. *Ecology and Society*. 25(2): 13. [10.5751/ES-11552-250213](https://doi.org/10.5751/ES-11552-250213). [[PDF](ms/CusackEtAl2020.pdf)]</li>
 
 <li>Minderman, J, JJ Cusack, **AB Duthie**, IL Jones, RA Pozo, OS Rakotonarivo, and N Bunnefeld. 2019. Decision trees for data publishing may exacerbate conservation conflict. *Nature Ecology and Evolution*. 3:318. [10.1038/s41559-019-0804-7](https://doi.org/10.1038/s41559-019-0804-7). [[PDF](ms/MindermanEtAl2019.pdf)]</li>
 
 <li>Cusack, JJ, **AB Duthie**, OS Rakotonarivo, RA Pozo, THE Mason, J Månsson, L Nilsson, R McKenzie, IM Tombre, E Eythórsson, J Madsen, A Tulloch, G Churchill, J Shaw, RD Hearn, S Redpath, and N Bunnefeld. 2019. Time series analysis reveals synchrony and asynchrony between conflict management effort and increasing large grazing bird populations in northern Europe. *Conservation Letters*. 12:e12450. [10.1111/conl.12450](http://onlinelibrary.wiley.com/doi/10.1111/conl.12450/full). [[PDF](ms/CusackEtAl2019.pdf)]</li>
 
 <li>**Duthie, AB**, JJ Cusack, J Minderman, IL Jones, EB Nilsen, RA Pozo, OS Rakotonarivo, B Van Moorter, and N Bunnefeld. 2018. GMSE: an R package for generalised management strategy evaluation. *Methods in Ecology and Evolution*. 9:2396-2401 [10.1111/2041-210X.13091](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13091). [[PDF](DuthieEtAl2108.pdf)] [[Pre-print](https://www.biorxiv.org/content/early/2018/08/23/221432)] [[S1](ms/DuthieEtAl2018_GMSE_SI1.pdf)] [[S2](ms/DuthieEtAl2018_GMSE_SI2.pdf)] [[S3](ms/DuthieEtAl2018_GMSE_SI3.pdf)] [[S4](ms/DuthieEtAl2018_GMSE_SI4.pdf)] [[S5](ms/DuthieEtAl2018_GMSE_SI5.pdf)] [[S6](ms/DuthieEtAl2018_GMSE_SI6.pdf)] [[S7](ms/DuthieEtAl2018_GMSE_SI7.pdf)] [[Code](https://github.com/confoobio/GMSE)] [[Website](https://confoobio.github.io/gmse/)]</li>
 
 <li>Paine, CET, A Deasey, and **AB Duthie**. 2018. Towards general mechanistic predictions of community dynamics. *Functional Ecology*. 32:1681-1692. [10.1111/1365-2435.13096](http://onlinelibrary.wiley.com/doi/10.1111/1365-2435.13096/full/). [[PDF](ms/PaineEtAl2018.pdf)]</li>

 <li>Redpath, SM, Andren, Z Baynham-Herd, N Bunnefeld, **AB Duthie**, J Frank, CA Garcia, A Keane, J Månsson, L Nilsson, CRJ Pollard, OS Rakotonarivo, CF Salk, and H Travers. 2018. Games as tools to address conservation conflicts. *Trends in Ecology and Evolution*. 33 (6):415-426. [10.1016/j.tree.2018.03.005](https://www.cell.com/trends/ecology-evolution/fulltext/S0169-5347(18)30059-4). [[PDF](ms/RedPathEtAl2018.pdf)]</li>

 <li>**Duthie, AB**, G Bocedi, RR Germain, and JM Reid. 2018. Evolution of pre-copulatory and post-copulatory strategies of inbreeding avoidance and associated polyandry. *Journal of Evolutionary Biology*. 31:31-45. [10.1111/jeb.13189](https://onlinelibrary.wiley.com/doi/10.1111/jeb.13189/full). [[PDF](ms/DuthieEtAl2017.pdf)] [[Pre-print](http://www.biorxiv.org/content/biorxiv/early/2017/09/24/136093.full.pdf)] [[Supporting Information](ms/DuthieEtAl2017_SI.pdf)] [[Code](https://github.com/bradduthie/pre_post_cop)]</li>
 
 <li>**Duthie, AB**, AM Lee, and JM Reid. 2016. Inbreeding parents should invest more resources in fewer offspring. *Proceedings of the Royal Society B*. 282:20161845. [10.1098/rspb.2016.1845](http://rspb.royalsocietypublishing.org/content/283/1843/20161845) [[PDF](ms/DuthieEtAl2016c.pdf)] [[Pre-print](http://biorxiv.org/content/early/2016/10/18/062794)] [[Supplementary Material](ms/DuthieEtAl2016c_SI.pdf)] [[Code](https://github.com/bradduthie/pre_post_cop)]</li>
 
 <li>**Duthie, AB**, and JM Reid. 2016. Evolution of inbreeding avoidance and inbreeding preference through mate choice among interacting relatives. *American Naturalist*. 188(6):651-667. [10.1086/688919](http://www.journals.uchicago.edu/doi/full/10.1086/688919) [[PDF](ms/Duthie_Reid2016.pdf)] [[Appendix A](ms/Duthie_Reid2016_AppendixA.pdf)] [[Appendix B](ms/Duthie_Reid2016_AppendixB.pdf)] [[Supplemental Material](Duthie_Reid2016_SM.pdf)] [[Code](https://github.com/bradduthie/Inbreeding)]</li>

<li>**Duthie, AB**, and JD Nason. 2016. Plant connectivity underlies plant-pollinator-exploiter distributions in *Ficus petiolaris* and associated pollinating and non-pollinating fig wasps. *Oikos*. 125(11):1597-1606. [10.1111/oik.02905](http://onlinelibrary.wiley.com/doi/10.1111/oik.02905/abstract) [[PDF](ms/Duthie_et_al_2016_Oikos.pdf)] [[Analysis](https://github.com/bradduthie/Duthie_and_Nason_2016)]</li>

<li>**Duthie, AB**, G Bocedi, and JM Reid. 2016. When does female multiple mating evolve to adjust inbreeding? Effects of inbreeding depression, direct costs, mating constraints, and polyandry as a threshold trait. *Evolution*. 70(9):1927-1943. [10.1111/evo.13005](http://onlinelibrary.wiley.com/doi/10.1111/evo.13005/abstract) [[PDF](ms/DuthieEtAl2016b.pdf)] [[Supporting Information S1](ms/DuthieEtAl2016_SI1.pdf)] [[Supporting Information S2](ms/DuthieEtAl2016_SI2.pdf)] [[Code](https://github.com/bradduthie/PolyInbreed)]</li>

 <li>Frater, PN, and **AB Duthie**. 2016. Power scaling, vascular branching patterns, and the golden ratio. *Ideas in Ecology and Evolution*. 9:15-18. [10.4033/iee.2016.9.4.n](http://ojs.library.queensu.ca/index.php/IEE/article/view/6312) [[PDF](ms/Frater_Duthie2016.pdf)]</li>
 
 <li>Reid, JM, G Bocedi, P Nietlisbach, **AB Duthie**, ME Wolak, EA Gow, and P Arcese. 2016. Variation in parent‐offspring kinship in socially monogamous systems with extra‐pair reproduction and inbreeding. *Evolution*. 70 (7):1512-1529. [10.1111/evo.12953](http://onlinelibrary.wiley.com/doi/10.1111/evo.12953/abstract) [[PDF](ms/ReidEtAl2016.pdf)]</li>
 
 <li>Reid, JM, P Arcese, G Bocedi, **AB Duthie**, ME Wolak, and LF Keller. 2015. Resolving the conundrum of inbreeding depression but no inbreeding avoidance: estimating sex-specific selection on inbreeding by song sparrows (*Melospiza melodia*). *Evolution*. 69 (11):2846-2861. [10.1111/evo.12780](http://onlinelibrary.wiley.com/doi/10.1111/evo.12953/abstract) [[PDF](ms/ReidEtAl2016_b)]</li>

 <li>**Duthie, AB**, KC Abbott, and JD Nason. 2015. Trade-offs and coexistence in fluctuating environments: evidence for a key dispersal-fecundity tradeoff in five nonpollinating fig wasps. *American Naturalist*. 186 (1):151-158.  [10.1086/681621](http://www.jstor.org/stable/10.1086/681621) [[PDF](ms/DuthieEtAl2015.pdf)] [[Appendix](ms/DuthieEtAl2015_Appendix.pdf)] [[Analysis](https://github.com/bradduthie/Duthie_et_al_2015)]</li>

 <li>Reid, JM, **AB Duthie**, ME Wolak, and P Arcese. 2015. Demographic mechanisms of inbreeding adjustment through extra-pair reproduction. *Journal of Animal Ecology*. 84 (4):1029-1040. [10.1111/1365-2656.12340](http://onlinelibrary.wiley.com/doi/10.1111/1365-2656.12340/abstract) [[PDF](ms/ReidEtAl2015b.pdf)]</li>
 
 <li>**Duthie, AB**, and JM Reid. 2015. What happens after inbreeding avoidance? Inbreeding by rejected relatives and the inclusive fitness benefit of inbreeding avoidance. *PLoS One*. 10 (4):e0125140. [10.1371/journal.pone.0125140](http://dx.plos.org/10.1371/journal.pone.0125140) [[PDF](ms/Duthie_Reid2015.pdf)] [[Supporting Information](ms/Duthie_Reid2015SI.pdf)] [[Analysis](https://github.com/bradduthie/Duthie_and_Reid_2015_Figs)]</li>

 <li>Duthie, AC, and **AB Duthie**. 2015. Do music and art influence one another? Measuring cross-modal similarities in music and art. *Polymath: An Interdisciplinary Arts and Sciences Journal*. 5 (1):1-22. [[PDF](ms/Duthie_Duthie2015.pdf)]</li>
 
 <li>Reid, JM, P Arcese, LF Keller, RR Germain, **AB Duthie**, S Losdat, ME Wolak, and P Nietlisbach. 2015. Quantifying inbreeding avoidance through extra-pair reproduction. *Evolution*. 69 (1):59-74. [10.1111/evo.12557](http://onlinelibrary.wiley.com/doi/10.1111/evo.12557/abstract) [[PDF](ms/ReidEtAl2015.pdf)]</li>
 
 <li>**Duthie, AB**, KC Abbott, and JD Nason. 2014. Trade-offs and coexistence: A lottery model applied to fig wasp communities. *American Naturalist* 183 (6):826-841. [10.1086/675897](http://www.jstor.org/stable/10.1086/675897) [[PDF](ms/DuthieEtAl2014.pdf)] [[Code](https://github.com/bradduthie/Duthie_et_al_2014)]</li>

 <li>**Duthie, AB**, and MR Falcy. 2013. The influence of habitat autocorrelation on plants and their seed-eating pollinators. *Ecological Modelling* 251:260-270. [10.1016/j.ecolmodel.2012.12.019](http://dx.doi.org/10.1016/j.ecolmodel.2012.12.019) [[Code](https://github.com/bradduthie/Duthie_and_Falcy_2013)]</li>

 <li>**Duthie, AB**. 2004. The fork and the paperclip: A memetic perspective. *Journal of Memetics - Evolutionary Models of Information Transmission*, 8 (1). [http://pcp.vub.ac.be/jom-emit/past.html](http://pcp.vub.ac.be/jom-emit/past.html) [[PDF](ms/Duthie2003.pdf)]</li> 

</ol>



