---
title: "Research"
---

<hr>


My research focuses on evolutionary, ecological, and social-ecological questions by developing theory using mathematical and computational (i.e., individual-based) modelling. Specific areas of interest include ecological community stability and coexistence, animal inbreeding and parental investment behaviour, and the dynamics of social-ecological systems under conflict. Current projects in which I am involved as a principle investigator, co-investigator, or associate member include the following:

- **Eco-evolutionary theory**: One area of my research focuses on addressing fundamental questions in ecological and evolutionary theory. I co-lead the Unification of Modern Coexistence Theory and Price Equation (UNICOP) project, which is funded by the French Foundation for Research on Biodiversity (FRB) and the German Centre for Integrative Biodiversity Research (iDiv). The [UNICOP project](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/unicop/) focuses on unifying theory concerning how shared processes shape the evolution and coexistence of biodiverse communities, and attempts to bridge gaps that currently exist among parallel theoretical frameworks.

- **Social-ecological modelling**: Another area of my research focuses on individual-based models of social-ecological systems. As part of the Enhancing Diversity to Overcome Resistance Evolution ([ENDORSE](https://enhancingdiversity.wixsite.com/endorse/project)) project, I developed the [resevol R package](https://bradduthie.github.io/resevol) to model the evolution of pesticide resistance in agricultural landscapes. The resevol package can model rich spatially explicit landscapes, covarying pest traits and full genomes, and different rotation regimes for crop and pesticide application. As part of the [ConFooBio](https://sti-cs.org/confoobio/) project, I led the development of the Generalised Management Strategy Evaluation ([GMSE](https://confoobio.github.io/gmse/)) social-ecological modelling R software package. GMSE integrates game theory and ecological theory to construct social-ecological models that simulate the management of populations and stakeholder actions.

- **Ecological Knowledge Games**: A third area of my research focuses on the integration of games with social-ecological models. I lead the [EcoKnowGames](https://ecoknowgames.github.io/) project, an inter-disciplinary research programme leveraging the technology of video games to evaluate sustainable development solutions and share diverse views on human development. A key goal of EcoKnowGames is to develop world-building games that are underpinned by realistic ecological models, from which player decision-making data can be collected and applied to hypothesis testing and model parameterisation. As part of the Restoring Ecosystems to Stop the Threat Of (Re-)Emerging Infectious Diseases ([RestoreID](https://restoreid.europamedia.org/)) project, I helped develop the game [Restore](https://glitchers.itch.io/restore) to better understand decision-making during ecosystem restoration.

I currently serve as an associate editor at the [Journal of Animal Ecology](https://besjournals.onlinelibrary.wiley.com/journal/13652656). I am a member of the [British Ecological Society](https://www.britishecologicalsociety.org/) and the [Association for the Study of Animal Behaviour](https://www.asab.org/).
