---
title: "Resources for statistics teachers"
---


If you are teaching statistics and using jamovi, or are interested in making the switch to jamovi, then please feel free to get in touch with me if you are interested in teaching materials. Below is a syllabus for introductory statistics with links to all learning materials. Lecture slides for weeks 6-8 are currently unavailable, and I plan to revise the practical content for Week 10. **If you want use this material for your own teaching and let me know, then I will prioritise getting it up and online** (I also have some video lectures made). Note that PPTX slides are designed for maximal accessibility with alt images and colours that get perfect accessibility scores on the Canvas learning management system. Images to get the Rmd files to knit are [available here](http://bradduthie.github.io/stats_teaching/stats_img.zip). All relevant files are publicly accessible [on GitHub](https://github.com/bradduthie/stats_teaching) (https://github.com/bradduthie/stats_teaching).

********************************************************************************

Week 1: Background mathematics and data organisation
==========================================================

- **Read:** [Chapter 1](https://bradduthie.github.io/stats/Chapter_1.html), [Chapter 2](https://bradduthie.github.io/stats/Chapter_2.html)
- **Audiobook:** [Chapter 1](https://open.spotify.com/episode/7n1aEJ7pA7GkrXG67KupbI?si=ylK99ydETBSsbrQ9zNaX-g), [Chapter 2](https://open.spotify.com/episode/3S0l7iUHf6r0vVJmADDMrQ?si=HdLds3sgTXeeDLmj4w3weg)
- **Slides:** Lecture 1A ([PDF](http://bradduthie.github.io/stats_teaching/Stats_1A.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_1A.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_1A.Rmd1)), Lecture 1B ([PDF](http://bradduthie.github.io/stats_teaching/Stats_1B.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_1B.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_1A.Rmd))
- **Practical:** [Chapter 3](https://bradduthie.github.io/stats/Chapter_3.html), [Audiobook Chapter 3](https://open.spotify.com/episode/1gkTKFcbARH8KY48ow2Zc9?si=76I1d4TbSj2SKuNPcsMFHA), [Worksheet](), [Answers](https://bradduthie.github.io/stats/appendexA.html#chapter-3)
- **Quiz:** [Quiz 1]()

********************************************************************************

Week 2: Statistical concepts
==========================================================

- **Read:** [Chapter 4](https://bradduthie.github.io/stats/Chapter_4.html), [Chapter 5](https://bradduthie.github.io/stats/Chapter_5.html), [Chapter 6](https://bradduthie.github.io/stats/Chapter_6.html), [Chapter 7](https://bradduthie.github.io/stats/Chapter_7.html)
- **Audiobook:** [Chapter 4](https://open.spotify.com/episode/3TURBHMtoSE3FLpul1OgsL?si=fxq578Q4SGK6IRJnVTjFrA), [Chapter 5](https://open.spotify.com/episode/05jaVzttOswsS31HKHwGLQ?si=tmOc0G-WSsm6OHPI_Q29WQ), [Chapter 6](https://open.spotify.com/episode/3sg0hjIBU8qv1E4nbSklUJ?si=QcS-2d7hT_GlcT5qNB8YRw), [Chapter 7](https://open.spotify.com/episode/0ZQEmLSLpkgG6qptFONzGd?si=k2eLqPjqTuWaWJ8MeWHEwQ)
- **Slides:** Lecture 2A ([PDF](http://bradduthie.github.io/stats_teaching/Stats_2A.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_2A.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_1A.Rmd)), Lecture 2B ([PDF](http://bradduthie.github.io/stats_teaching/Stats_2B.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_2B.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_1A.Rmd))
- **Practical:** [Chapter 8](https://bradduthie.github.io/stats/Chapter_8.html), [Audiobook Chapter 8](https://open.spotify.com/episode/0YHFt8q4AnDdV4H7TOqvui?si=saRY6cnFR-uKt9oAs2EWqw), [Worksheet](), [Answers](https://bradduthie.github.io/stats/appendexA.html#chapter-8)
- **Quiz:** [Quiz 2]()

********************************************************************************

Week 3: Summary statistics
==========================================================

- **Read:** [Chapter 9](https://bradduthie.github.io/stats/Chapter_9.html), [Chapter 10](https://bradduthie.github.io/stats/Chapter_10.html), [Chapter 11](https://bradduthie.github.io/stats/Chapter_11.html), [Chapter 12](https://bradduthie.github.io/stats/Chapter_12.html), [Chapter 13](https://bradduthie.github.io/stats/Chapter_13.html)
- **Audiobook:** [Chapter 9](https://open.spotify.com/episode/1hZ03pza4C4p8kkU291glu?si=M3jzISkSTV64HPg5Ab0IIg), [Chapter 10](https://open.spotify.com/episode/3f01iW8yriw9JY51wxiGWC?si=IoaqtEUiQBy3BqAUjyxKCg), [Chapter 11](https://open.spotify.com/episode/5E5aPrOHLDU9LdBTQDkrJg?si=vpyO0XlTSEi7ubP5UUQOdQ), [Chapter 12](https://open.spotify.com/episode/37mzmBP3hMYwMzhQqCIGMg?si=hSGVMMr9TUil3P4jLqAG1g), [Chapter 13](https://open.spotify.com/episode/0FwPKpbU0Q9L6FHRWx9ryo?si=zJ7BceuNTzW2qCL400bJzQ)
- **Slides:** Lecture 3A ([PDF](http://bradduthie.github.io/stats_teaching/Stats_3A.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_3A.pdf)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_1A.Rmd)), Lecture 3B ([PDF](http://bradduthie.github.io/stats_teaching/Stats_3B.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_3B.pdf)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_3B.Rmd))
- **Practical:** [Chapter 14](https://bradduthie.github.io/stats/Chapter_14.html), [Audiobook Chapter 14](https://open.spotify.com/episode/1a6sKiQqSGgm7utj8gZrJl?si=ivpS0rc6TQqQfRaqz_M9oQ), [Worksheet](), [Answers](https://bradduthie.github.io/stats/appendexA.html#chapter-14)
- **Shiny Apps**: [[Building a histogram](https://bradduthie.github.io/stats/app/build_histogram/)], [[Intuitive mean and standard deviation](https://bradduthie.github.io/stats/app/forest/)], [[Mean and standard deviation on a histogram](https://bradduthie.github.io/stats/app/normal_pos_neg/)]
- **Quiz:** [Quiz 3]()

********************************************************************************

Week 4: Probability models and the central limit theorem
==========================================================

- **Read:** [Chapter 15](https://bradduthie.github.io/stats/Chapter_15.html), [Chapter 16](https://bradduthie.github.io/stats/Chapter_16.html)
- **Audiobook:** [Chapter 15](https://open.spotify.com/episode/67UQGLy1aEmYYxzziX1eZi?si=KeF2NFsTQmKKq9_t1V_BkA), [Chapter 16](https://open.spotify.com/episode/32XD0izP0TQeI9H9RxHE1k?si=bM1lhJNxRLGCubM1p78vrw)
- **Slides:** Lecture 4A ([PDF](http://bradduthie.github.io/stats_teaching/Stats_4A.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_4A.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_4A.Rmd)), Lecture 4B ([PDF](http://bradduthie.github.io/stats_teaching/Stats_4B.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Stats_4B.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_4B.Rmd))
- **Practical:** [Chapter 17](https://bradduthie.github.io/stats/Chapter_17.html), [Audiobook Chapter 17](https://open.spotify.com/episode/7osFrPXyKNi6su7C35rso2?si=kAYzCJNtRn6jemN9ir3cJA), [Worksheet](), [Answers](https://bradduthie.github.io/stats/appendexA.html#chapter-17)
- **Shiny App**: [[Visualising z-scores and p-values](https://bradduthie.github.io/stats/app/zandp/)]
- **Quiz:** [Quiz 4]()

********************************************************************************

Week 5: Statistical inference
==========================================================

- **Read:** [Chapter 18](https://bradduthie.github.io/stats/Chapter_18.html), [Chapter 19](https://bradduthie.github.io/stats/Chapter_19.html)
- **Audiobook:** [Chapter 18](https://open.spotify.com/episode/63pFvrOGHSwPQmwKZhtlmH?si=pvkVt-M7QLCNYervAftztA), [Chapter 19](https://open.spotify.com/episode/3JEN5nYmPkxh9tdN456ode?si=NelqB4TSS6-p_QEZWB46-w)
- **Slides:** Lecture 5A ([PDF](http://bradduthie.github.io/stats_teaching/Stats_5A.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_5A.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_5A.Rmd)), Lecture 5B ([PDF](http://bradduthie.github.io/stats_teaching/Stats_5B.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_5B.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_5B.Rmd))
- **Practical:** [Chapter 20](https://bradduthie.github.io/stats/Chapter_20.html), [Audiobook Chapter 20](https://open.spotify.com/episode/6EfD3dLbaps5RqlRDCcmK1?si=S2NdLb0DSseNLDXXNdOMbQ), [Worksheet](), [Answers](https://bradduthie.github.io/stats/appendexA.html#chapter-20)
- **Shiny Apps**: [[Visualising confidence intervals](https://bradduthie.github.io/stats/app/CI_hist_app/)], [[The t-distribution](https://bradduthie.github.io/stats/app/CI_hist_app/)]
- **Quiz:** [Quiz 5]()

********************************************************************************

Week 6: Hypothesis testing
==========================================================

- **Read:** [Chapter 21](https://bradduthie.github.io/stats/Chapter_21.html), [Chapter 22](https://bradduthie.github.io/stats/Chapter_22.html)
- **Audiobook:** [Chapter 21](https://open.spotify.com/episode/2oNIDMzto0px0dbgY2FBge?si=CDCf_DvsS8C2hf9KQTMZBQ), [Chapter 22](https://open.spotify.com/episode/1PgkllbKmPEi3JAyBEzgR3)
- **Slides:** Lecture 6A (PDF) (PPTX) (Rmd), Lecture 6B (PDF) (PPTX) (Rmd)
- **Practical:** [Chapter 23](https://bradduthie.github.io/stats/Chapter_23.html), [Audiobook Chapter 23](https://open.spotify.com/episode/1AYHCuqDcsvmetkrxruQtS?si=Q-cB3iPxQjubLSMdtZiF6A), [Worksheet](), [Answers](https://bradduthie.github.io/stats/appendexA.html#chapter-23)
- **Quiz:** [Quiz 6]()

********************************************************************************

Week 7: Analysis of Variance
==========================================================

- **Read:** [Chapter 24](https://bradduthie.github.io/stats/Chapter_24.html), [Chapter 25](https://bradduthie.github.io/stats/Chapter_25.html), [Chapter 26](https://bradduthie.github.io/stats/Chapter_26.html), [Chapter 27](https://bradduthie.github.io/stats/Chapter_27.html)
- **Audiobook:** [Chapter 24](https://open.spotify.com/episode/6jNRZSa7IjWaOlsgbQTVzN?si=JIu-980eTXSs_qO9Eo-Ovw), [Chapter 25](https://open.spotify.com/episode/3zbvUEyVclUdNzWplgoqGg?si=qCHIzDR8QHqqKS3fdEY7fg), [Chapter 26](https://open.spotify.com/episode/5JRboY3XSWfPpxdoFeBmps?si=-7vmmOheTUy0gzfKNeBHGQ), [Chapter 27](https://open.spotify.com/episode/27lEc6kApQphXg60VhWuRo?si=d1p2IO37S1yZV9nnaLquBA)
- **Slides:** Lecture 7A (PDF) (PPTX) (Rmd), Lecture 7B (PDF) (PPTX) (Rmd)
- **Practical:** [Chapter 28](https://bradduthie.github.io/stats/Chapter_28.html), [Audiobook Chapter 28](https://open.spotify.com/episode/7fwD9bbYq6a27HktI5WpRE?si=F1hplgEdQMmKS6cCs0uGkQ), [Worksheet](), [Answers](https://bradduthie.github.io/stats/appendexA.html#chapter-28)
- **Shiny App**: [[Visualising the F distribution](https://bradduthie.github.io/stats/app/f_distribution/)]
- **Quiz:** [Quiz 7]()

********************************************************************************

Week 8: Counts and correlation
==========================================================

- **Read:** [Chapter 29](https://bradduthie.github.io/stats/Chapter_29.html), [Chapter 30](https://bradduthie.github.io/stats/Chapter_30.html)
- **Audiobook:** [Chapter 29](https://open.spotify.com/episode/0oW7trDLKE6aV2oeGA2Q0A?si=8ri0grhsT1i0T-elLQPz6g), [Chapter 30](https://open.spotify.com/episode/4xu9AWUqYSp4buwtVicANo?si=yex1mZ-7RVOiqNrtouFkNA)
- **Slides:** Lecture 8A (PDF) (PPTX) (Rmd), Lecture 8B ([PDF](http://bradduthie.github.io/stats_teaching/Stats_8B.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_8B.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_8B.Rmd))
- **Practical:** [Chapter 31](https://bradduthie.github.io/stats/Chapter_31.html), [Audiobook Chapter 31](https://open.spotify.com/episode/1Z9ie6ZvtxaIzih6dmAsVS), [Worksheet](), [Answers](https://bradduthie.github.io/stats/appendexA.html#chapter-31)
- **Shiny Apps**: [[Visualising the Chi-square distribution](https://bradduthie.github.io/stats/app/chi-square/)], [[Visualising correlation](https://bradduthie.github.io/stats/app/corr_click/)]
- **Quiz:** [Quiz 8]()

********************************************************************************

Week 9: Linear Regression
==========================================================

- **Read:** [Chapter 32](https://bradduthie.github.io/stats/Chapter_32.html), [Chapter 33](https://bradduthie.github.io/stats/Chapter_33.html)
- **Audiobook:** [Chapter 32](https://open.spotify.com/episode/72qgQ1GArI0Tiixn2Y6p3J?si=gSA2MVggTGO56OB6CaZ8NQ), [Chapter 33](https://open.spotify.com/episode/69DGMSLZkB4fK0WmPwLVkr?si=bMB2qvnvTMudWJJNVopKJg)
- **Slides:** Lecture 9A ([PDF](http://bradduthie.github.io/stats_teaching/Stats_9A.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_9A.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_9A.Rmd)), Lecture 9B ([PDF](http://bradduthie.github.io/stats_teaching/Stats_9B.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_9B.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_9B.Rmd))
- **Practical:** [Chapter 34](https://bradduthie.github.io/stats/Chapter_34.html), [Audiobook Chapter 34](https://open.spotify.com/episode/7Ffm1UQSFaO3C6gw9fe8JD?si=94ZM7k8hTraCA48QLwLqxg), [Worksheet](), [Answers](https://bradduthie.github.io/stats/appendexA.html#chapter-34)
- **Shiny App**: [[Thinking about regression](https://bradduthie.github.io/stats/app/regr_click/)]
- **Quiz:** [Quiz 9]()

********************************************************************************

Week 10: Randomisation
==========================================================

- **Read:** [Chapter 35](https://bradduthie.github.io/stats/Chapter_35.html)
- **Audiobook:** [Chapter 35](https://open.spotify.com/episode/6XqgOCCBPvMWP5AdRvt8tV?si=QtKz7kMVRWaDstRYrYcppg)
- **Slides:** Lecture 10A ([PDF](http://bradduthie.github.io/stats_teaching/Stats_10A.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_10A.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_10A.Rmd)), Lecture 10B ([PDF](http://bradduthie.github.io/stats_teaching/Stats_10B.pdf)) ([PPTX](http://bradduthie.github.io/stats_teaching/Lecture_10B.pptx)) ([Rmd](http://bradduthie.github.io/stats_teaching/Stats_10B.Rmd))
- **Practical**: [Introduction to R](https://bradduthie.github.io/SCIU4T4/Chapter_36.html), [Statistical tests in R](https://bradduthie.github.io/SCIU4T4/Chapter_38.html)
- **Shiny App**: [[Understanding randomisation](https://bradduthie.github.io/stats/app/randomisation/)]
- **Quiz:** [Quiz 10]()

********************************************************************************

I am planning to develop a jamovi module for the Week 11 content on randomisation approaches to statistical hypothesis testing.  The R code that I have for assessments can generate custom datasets with statistical properties customised for each test or exam, meaning that any number of unique datasets can be created (e.g., one for each student with unique correct answers). I also have Rmarkdown scripts that can produce custom feedback reports for each student (this might need to be modified before use).