---
title: "Teaching"
---

<hr>

As an educator, I take a learning-centred approach to guide students through course material. To teach effectively, I believe that it is necessary to understand how people learn. Learning is a biological process that happens in the brain. When we learn, we are connecting new ideas to ones with which we are already familiar. This process requires that students think actively. As such, to maximise the amount of learning in a classroom, I use teaching techniques designed to maximise student thinking about biological concepts, building upon their knowledge from prior education and their individual life experiences. Thinking is done individually, so each individual is ultimately responsible for their own learning, but the conditions for new learning can be facilitated by social interactions and a positive learning environment.

<hr>

## Teaching activity


I hold the following professional teaching qualifications:

- Fellow of the Higher Education Academy ([FHEA](https://www.advance-he.ac.uk/fellowship/fellowship))
- Graduate Student Teaching Certificate ([Iowa State University](https://www.iastate.edu/))


At the [University of Stirling](https://www.stir.ac.uk/), I am the director of the following programmes:

- [Biology](https://www.stir.ac.uk/courses/ug/biology/)
- [Animal Biology](https://www.stir.ac.uk/courses/ug/animal-biology/)
- Biology and Mathematics

I coordinate the following modules:

- Statistical Techniques (SCIU4T4)
- Evolution and Genetics (BIOU3GE)


I contribute to the following modules:

- Behavioural Ecology (BIOU6BE)
- Biology Field Course (SCIU3FB)
- Honours Research Dissertation (BIOU9PR)


I am also currently the primary supervisor of 2 PhD students and secondary supervisor for 4 PhD students.

<hr>

## Professional development

As a FHEA, I serve the University of Stirling Framework Evidencing Learning and Teaching Enhancement (SFELTE) as a mentor, referee, and reviewer for new HEA applicants.

I am also the neurodiversity lead champion for the Visibility of Inclusion for Boosting Equity (VIBE) initiative, which provides additional support for neurodivergent students in the Biological and Environmental Sciences.



